import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Requisições HTTP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav>
          <ul>
            <li>
              <a href="Axios">Axios</a>
            </li>
            <li>
              <a href="Fetch">Fetch</a>
            </li>
          </ul>
        </nav>
      </main>
    </div>
  );
}
